#!/bin/bash

# server
#
# This bash script file contains the command to launch a docker
# container for local development and testing of this application.
#
# Author: Kenny Carlile (KCarlile.com)
# Source: https://github.com/KCarlile/jekyll-twitter-bootstrap-static

echo ""
echo "================================================================================"
echo "This script checks for the proper /etc/hosts entry and then launches the"
echo "Docker container defined in Dockerfile and docker-compose.yml."
echo ""
echo "URL: http://jekyll-twitter-bootstrap-static.local"
echo "================================================================================"
echo ""
echo ""

if ! grep -q "jekyll-twitter-bootstrap-static.local" /etc/hosts; then
    echo "There is no entry in /etc/hosts for jekyll-twitter-bootstrap-static.local."
    echo "Please run 'sudo ./setup-etc-hosts'."
    exit
fi

docker compose up --build